name: Deploy Supabase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy Supabase Functions
        env:
              SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
            for function in site/functions/supabase/*/index.ts; do
                function_name=$(basename $(dirname $function))
                npx supabase functions deploy $function_name --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
            done
